# Generated by Django 4.2.4 on 2023-09-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Пациент", "verbose_name_plural": "Пациенты"},
        ),
    ]
