# Generated by Django 4.2.4 on 2023-09-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Описание"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="Дата постановки диагноза"
                    ),
                ),
                ("complaints", models.TextField(max_length=500, verbose_name="Жалобы")),
                (
                    "objective_status",
                    models.TextField(max_length=500, verbose_name="Объективный статус"),
                ),
                ("treatment", models.TextField(max_length=500, verbose_name="Лечение")),
                ("prognosis", models.TextField(max_length=500, verbose_name="Прогноз")),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosticStudies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Описание"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=None,
                        null=True,
                        verbose_name="Дата проведения манипуляции",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(max_length=20, verbose_name="Отчество"),
                ),
                ("last_name", models.CharField(max_length=20, verbose_name="Фамилия")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "specialization",
                    models.CharField(max_length=200, verbose_name="Специализация"),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to="images/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "diagnostics",
                    models.ManyToManyField(
                        related_name="doctors",
                        related_query_name="doctor",
                        to="main.diagnosticstudies",
                        verbose_name="Диагностические манипуляции",
                    ),
                ),
                (
                    "diseases",
                    models.ManyToManyField(
                        related_name="doctors",
                        related_query_name="doctor",
                        to="main.diagnosis",
                        verbose_name="Заболевания",
                    ),
                ),
            ],
        ),
    ]
