# Generated by Django 4.2.4 on 2023-09-18 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="patients",
            field=models.ManyToManyField(
                related_name="doctors",
                related_query_name="doctor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пациенты",
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="diagnosticstudies",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="diagnosis",
                to="main.diagnosticstudies",
                verbose_name="Диагностические исследования",
            ),
        ),
    ]
