# Generated by Django 4.2.4 on 2023-09-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticstudies",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Стоимость"),
        ),
    ]
