# Generated by Django 4.2.4 on 2023-09-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_doctor_diseases_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
